name: gostin

channels:
  - conda-forge
  - defaults
dependencies:
  - pyvista
  - verde
  - pooch
  - harmonica
  - boule
  - rockhound
  - simpeg
  - emg3d
  - ipython
  - jupyter
  - matplotlib
  - python
  - scooby
  - segyio
  - xarray
  - pip
  - pip:
      - gempy
