name: empot

channels:
  - conda-forge
  - defaults
dependencies:
  - verde
  - pooch
  - harmonica
  - boule
  - rockhound
  - simpeg
  - emg3d
  - ipython
  - jupyter
  - matplotlib
  - python
  - scooby
  - segyio
  - xarray
  - pip
  - pip:
      - vtk==8.1.2 # Temporary!
      - pyvista
      - gempy
