name: gostin

channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - verde
  - pooch
  - harmonica
  - boule
  - rockhound
  - simpeg
  - emg3d
  - pygimli >=1.1.0
  - ipython
  - jupyter
  - matplotlib
  - python
  - scooby
  - segyio
  - xarray
  - pip
  - pip:
      - gempy
      - pyvista
