name: gostin

channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7 # No py38 vtk wheel on PyPI
  - verde
  - pooch
  - harmonica
  - boule
  - rockhound
  - simpeg
  - emg3d
  - matplotlib
  - scooby
  - segyio
  - xarray
  - pip
  - mkl-service # Gempy (Theano) throws a warning
  - pip:
      - vtk==8.1.2 # Temporary!
      - pyvista
      - gempy
